# Generated by Django 5.1 on 2024-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='developer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='is_bestselling',
            field=models.BooleanField(default=False),
        ),
    ]
