# Generated by Django 5.1 on 2024-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catlog', '0002_app_developer_app_is_bestselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
